# Generated by Django 3.0.6 on 2020-05-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleSettings',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('position', models.CharField(choices=[('site', 'عنوان سایت'), ('navbar', 'لوگو منو اصلی'), ('copyright', 'کپی رایت')], max_length=50, primary_key=True, serialize=False, verbose_name='موقعیت در سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='blog.Category', verbose_name='دسته بندی'),
        ),
    ]
